---

spring:
  profiles: dev

server:
  error.whitelabel.enabled: true
  port: 8080
  servlet.context-path: /spreg

dev.enabled: false

connector.rpc:
  perun_user: "user"
  perun_password: "pass"
  perun_url: "https://perun-dev.cesnet.cz/ba/rpc"
  request_timeout: 30000
  connection_timeout: 60000
  socket_timeout: 60000
  max_connections: 20
  max_connections_per_route: 18

jdbc:
  driver: "com.mysql.cj.jdbc.Driver"
  url: "jdbc:mysql://127.0.0.1:3306/spreg"
  username: "user"
  password: "pass"

application:
  admin_ids: [1, 2, 3]
  proxy_identifier: "https://login.cesnet.cz/idp/"
  protocols_enabled: ["oidc", "saml"]
  languages_enabled: ["en", "cs"]
  host_url: "http://spreg.com/spreg"
  secret_key: "secretSaltGoesHere123!X$"
  logout_url: "https://spreg.aai.cesnet.cz/Shibboleth.sso/Logout?target=https%3A%2F%2Fspreg.aai.cesnet.cz%2Fspreg%2F"
  mails_config_file_path: "/etc/perun-spreg/mails.yml"
  sp_managers_vo_id: 1
  sp_managers_parent_group_id: 1
  startup_sync_enabled: false

attributes:
  names:
    user_email: "urn:perun:user:attribute-def:def:preferredMail"
    proxy_identifier: "urn:perun:facility:attribute-def:def:proxyIdentifiers"
    master_proxy_identifier: "urn:perun:facility:attribute-def:def:masterProxyIdentifier"
    is_test_sp: "urn:perun:facility:attribute-def:def:isTestSp"
    show_on_service_list: "urn:perun:facility:attribute-def:def:showOnServiceList"
    administrator_contact: "urn:perun:facility:attribute-def:def:administrationContact"
    oidc_client_id: "urn:perun:facility:attribute-def:def:OIDCClientID"
    oidc_client_secret: "urn:perun:facility:attribute-def:def:OIDCClientSecret"
    entity_id: "urn:perun:facility:attribute-def:def:entityID"
    is_oidc: "urn:perun:facility:attribute-def:def:isOidcFacility"
    is_saml: "urn:perun:facility:attribute-def:def:isSamlFacility"
    service_name: "urn:perun:facility:attribute-def:def:serviceName"
    service_desc: "urn:perun:facility:attribute-def:def:serviceDescription"
  values:
    proxy_identifier: "XYZ"
    master_proxy_identifier: "https://login.cesnet.cz/idp/"

input_config_file_paths:
  service: "/etc/perun-spreg/attrs/service.yml"
  organization: "/etc/perun-spreg/attrs/org.yml"
  saml: "/etc/perun-spreg/attrs/saml.yml"
  oidc: "/etc/perun-spreg/attrs/oidc.yml"
  access_control: "/etc/perun-spreg/attrs/access_control.yml"

approvals:
  confirmation_period:
    days: 30
    hours: 0
  admins_endpoint: "https://dev.spreg.aai.cesnet.cz/spreg/auth/facilities/addAdmin/sign"
  authorities_endpoint: "https://dev.spreg.aai.cesnet.cz/spreg/auth/sign"
  transfer_authorities:
    allow_input: true
    default_entries:
      - "proxy@cesnet.cz"
    selection_entries:
      - display_value: "CESNET AAI administrators"
        emails: ["login@cesnet.cz"]

frontend:
  footer_html: "<h2>Dev footer</h2>"
  header_html: "<h2>Dev header</h2>"
  header_title: "Registration of SP - dev"
  header_logo_url: "https://perun.cesnet.cz/signpost/images/perun_3.png"
