---

spring:
  main:
    allow-bean-definition-overriding: true

server:
  error.whitelabel.enabled: false
  port: @server.port@
  servlet.context-path: @server.contextPath@

dev:
  enabled: false

connector.rpc:
  perun_user: "user"
  perun_password: "pass"
  perun_url: "https://perun-dev.cesnet.cz/ba/rpc"
  request_timeout: 30000
  connection_timeout: 60000
  socket_timeout: 60000
  max_connections: 20
  max_connections_per_route: 18

jdbc:
  driver: "com.mysql.cj.jdbc.Driver"
  url: "jdbc:mysql://127.0.0.1:3306/spreg"
  username: "user"
  password: "pass"

application:
  admin_ids: [1, 2, 3]
  proxy_identifier: "https://login.cesnet.cz/idp/"
  protocols_enabled: ["oidc", "saml"]
  languages_enabled: ["en", "cs"]
  host_url: "http://spreg.com/spreg"
  secret_key: "secretSaltGoesHere123!X$"
  logout_url: "https://spreg.aai.cesnet.cz/Shibboleth.sso/Logout?target=https%3A%2F%2Fspreg.aai.cesnet.cz%2Fspreg%2F"
  mails_config: "/etc/perun-spreg/mails.yml"

attributes:
  user_email_attr_name: "urn:perun:user:attribute-def:def:preferredMail"
  proxy_identifier_attr_name: "urn:perun:facility:attribute-def:def:proxyIdentifiers"
  proxy_identifier_attr_value: "XYZ"
  master_proxy_identifier_attr_name: "urn:perun:facility:attribute-def:def:masterProxyIdentifier"
  master_proxy_identifier_attr_value: "https://login.cesnet.cz/idp/"
  is_test_sp_attr_name: "urn:perun:facility:attribute-def:def:isTestSp"
  show_on_service_list_attr_name: "urn:perun:facility:attribute-def:def:showOnServiceList"
  administrator_contact_attr_name: "urn:perun:facility:attribute-def:def:administrationContact"
  oidc_client_id_attr_name: "urn:perun:facility:attribute-def:def:OIDCClientID"
  oidc_client_secret_attr_name: "urn:perun:facility:attribute-def:def:OIDCClientSecret"
  entity_id_attr_name: "urn:perun:facility:attribute-def:def:entityID"
  is_oidc_attr_name: "urn:perun:facility:attribute-def:def:isOidcFacility"
  is_saml_attr_name: "urn:perun:facility:attribute-def:def:isSamlFacility"
  service_name_attr_name: "urn:perun:facility:attribute-def:def:serviceName"
  service_desc_attr_name: "urn:perun:facility:attribute-def:def:serviceDescription"
  service_attributes_config: "/etc/perun-spreg/attrs/service.yml"
  organization_attrs_config: "/etc/perun-spreg/attrs/org.yml"
  saml_attrs_config: "/etc/perun-spreg/attrs/saml.yml"
  oidc_attrs_config: "/etc/perun-spreg/attrs/oidc.yml"
  ac_attrs_config: "/etc/perun-spreg/attrs/access_control.yml"

approvals:
  confirmation_period_days: 30
  confirmation_period_hours: 0
  specify_own: true
  admins_endpoint: "https://dev.spreg.aai.cesnet.cz/spreg/auth/facilities/addAdmin/sign"
  authorities_endpoint: "https://dev.spreg.aai.cesnet.cz/spreg/auth/sign"
  transfer_authorities:
    - display_value: "CESNET AAI administrators"
      emails: ["login@cesnet.cz"]

frontend:
  footer_html: ""
  header_html: ""
  header_title: "Registration of SP - dev"
  header_logo_url: "https://perun.cesnet.cz/signpost/images/perun_3.png"
